freebsd_instance:
  image_family: freebsd-13-0-snap

env:
  LISP: sbcl

task:
  preinstall_script:
    - pkg install -y curl git
  install_script:
    - curl -L https://raw.githubusercontent.com/shamazmazum/cl-cirrus/master/install.sh | sh
    - git clone --depth=1 git://github.com/shamazmazum/codex.git ~/lisp/codex
    - git clone --depth=1 git://github.com/shamazmazum/docparser.git ~/lisp/docparser
  script:
    - cl -f $CIRRUS_WORKING_DIR/tests/travis.lisp
    - cl -l codex -e '(codex:document :easy-audio :skip-undocumented t)'
