freebsd_instance:
  image_family: freebsd-14-0

env:
  LISP: sbcl-bin

task:
  preinstall_script:
    - pkg install -y git roswell gmake
  install_script:
    - mkdir -p ~/.roswell/local-projects
    - git clone --depth=1 https://github.com/shamazmazum/codex.git ~/.roswell/local-projects/codex
    - git clone --depth=1 https://github.com/shamazmazum/docparser.git ~/.roswell/local-projects/docparser
  script:
    - ros -l $CIRRUS_WORKING_DIR/tests/travis.lisp
    - ros -s codex -e '(codex:document :easy-audio :skip-undocumented t)'
